In [1]:
import pandas as pd
import numpy as np

In [2]:
# Definiujemy źródło danych oryginalnych
SOURCE_FILE = 'datasets/pawel_video_dataset.csv'

# Definiujemy ścieżkę do zapisu danych augmentowanych
TARGET_FILE = 'datasets/pawel_video_dataset_multiplications/pawel_video_dataset_moved_221_69.csv'

# Definiujemy maksymalne losowe przesunięcie w osiach x, y, z
przesuniecie_x_max = 0.02
przesuniecie_y_max = 0.02
przesuniecie_z_max = 0.01

In [3]:
df = pd.read_csv(SOURCE_FILE)
original_df_head = df.head()
original_df_head

,x00,x01,x02,x03,x04,x05,x06,x07,x08,x09,...,P,Q,R,S,T,U,V,W,X,Y
0,0.062401,0.156754,0.240973,0.281001,0.228892,0.184749,0.229520,0.237229,0.228040,0.122825,...,0,0,0,0,0,0,0,0,0,0
1,0.067616,0.162363,0.239966,0.277550,0.224153,0.183917,0.225444,0.227197,0.216072,0.122383,...,0,0,0,0,0,0,0,0,0,0
2,0.067081,0.163151,0.244303,0.278628,0.223035,0.185523,0.227478,0.230063,0.220079,0.123192,...,0,0,0,0,0,0,0,0,0,0
3,0.066214,0.161817,0.241138,0.277810,0.222872,0.184724,0.225877,0.226867,0.214742,0.122685,...,0,0,0,0,0,0,0,0,0,0
4,0.063990,0.160725,0.241852,0.277023,0.223015,0.183421,0.224416,0.230322,0.223434,0.122146,...,0,0,0,0,0,0,0,0,0,0

In [4]:
for i in range(21):
    for coord in ['x', 'y', 'z']:
        col_name = f'{coord}{i:02d}'
        if coord == 'z':
            przesuniecie_max = przesuniecie_z_max
        elif coord == 'y':
            przesuniecie_max = przesuniecie_y_max
        else:
            przesuniecie_max = przesuniecie_x_max
        
        # Losujemy przesunięcie dla całej kolumny zawierającej współrzędne jednego z punktów charakterystycznych
        przesuniecie = np.random.uniform(-przesuniecie_max, przesuniecie_max, df.shape[0])
        
        # Dodajemy przesunięcie do współrzędnych
        df[col_name] += przesuniecie
df.head()

,x00,x01,x02,x03,x04,x05,x06,x07,x08,x09,...,P,Q,R,S,T,U,V,W,X,Y
0,0.049776,0.166044,0.234874,0.264071,0.213611,0.181014,0.237000,0.245216,0.214325,0.117244,...,0,0,0,0,0,0,0,0,0,0
1,0.048385,0.146195,0.222384,0.275818,0.212160,0.199518,0.209088,0.241331,0.227947,0.123309,...,0,0,0,0,0,0,0,0,0,0
2,0.064422,0.173097,0.252173,0.280574,0.211260,0.185487,0.243796,0.210180,0.219465,0.127482,...,0,0,0,0,0,0,0,0,0,0
3,0.058815,0.171645,0.233888,0.272199,0.218387,0.199923,0.215255,0.240317,0.227821,0.123585,...,0,0,0,0,0,0,0,0,0,0
4,0.072859,0.166018,0.244681,0.268056,0.221044,0.170825,0.207467,0.214625,0.217320,0.141944,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df.to_csv(TARGET_FILE, index=False)